export const TABLE_RESIZE = 'COL_RESIZE';
export const CHANGE_TEXT = 'CHANGE_TEXT';
export const CHANGE_TABLE_NAME = 'CHANGE_TABLE_NAME';
export const APPLY_STYLE = 'APPLY_STYLE';
export const CURRENT_STYLES = 'CURRENT_STYLES';

